version: "3.7"

volumes:
  postgres_data:
  redis_data:

services:
  redis:
    image: redis:5.0-alpine
    ports:
      - ${CONSUME_LOCAL_REDIS_PORT:-6379}:6379
    volumes:
      - redis_data:/data
    command: redis-server
  postgres:
    image: postgres:10.6-alpine
    ports:
      - ${CONSUME_LOCAL_PGPORT:-5432}:5432
    volumes:
      # We'll store the postgres data in the 'postgres_data' volume we defined:
      - postgres_data:/var/lib/postgresql/data
      # Mount the database dumps folder:
      - ./db/dumps:/db/dumps
      # Mount the 'dumpdb' script
      - ./bin/dumpdb:/bin/dumpdb:ro
      # Mount the 'restoredb' script
      - ./bin/restoredb:/bin/restoredb:ro
    environment:
      POSTGRES_PASSWORD: 3x4mpl3P455w0rd

  # Where are the rest of the app services? (i.e. test, worker, web, etc)
  #
  # We've separated the app services from the rest of the services to streamline
  # the CI/CD pipeline execution. You'll find the app service definitions on the
  # `docker-compose.override.yml` file.
  #
  # You don't have to do anything special to docker-compose or plis to make the
  # project work as usual. By default, `docker-compose` will read
  # `docker-compose.yml` and `docker-compose.override.yml` files, merging their
  # contents before doing any actual work.
  #
  # See https://docs.docker.com/compose/extends/#understanding-multiple-compose-files